apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpro-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sarang095/Kube-AppDep.git
    targetRevision: master
    path: ./vpro-charts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
